<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="ARS-NBT-LAP-068" name="com.signdrive.testcases.Initiate_NewCase_Test" tests="7" failures="0" timestamp="26 May 2022 02:42:03 GMT" time="244.174" errors="1">
  <testcase name="signDriveLogin" time="2.983" classname="com.signdrive.testcases.Initiate_NewCase_Test"/>
  <testcase name="loginBgvEmail" time="4.585" classname="com.signdrive.testcases.Initiate_NewCase_Test">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.signdrive.testcases.Initiate_NewCase_Test.loginBgvEmail(Initiate_NewCase_Test.java:134)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </error>
  </testcase> <!-- loginBgvEmail -->
  <testcase name="initiateViaCandidate" time="20.458" classname="com.signdrive.testcases.Initiate_NewCase_Test"/>
  <testcase name="addCandidateInformation" time="26.546" classname="com.signdrive.testcases.Initiate_NewCase_Test"/>
  <testcase name="uploadCTCFile" time="30.748" classname="com.signdrive.testcases.Initiate_NewCase_Test"/>
  <testcase name="emailVerification" time="55.836" classname="com.signdrive.testcases.Initiate_NewCase_Test"/>
  <testcase name="verifyOLAcceptedByCandidate" time="103.018" classname="com.signdrive.testcases.Initiate_NewCase_Test"/>
</testsuite> <!-- com.signdrive.testcases.Initiate_NewCase_Test -->
